In [1]:
import pandas as pd

Step 1: Read data

In [2]:
df = pd.read_parquet("../data/samples/sample_1m.parquet")
df.head()

,timestamp,uid,campaign,conversion,conversion_timestamp,conversion_id,attribution,click,click_pos,click_nb,...,time_since_last_click,cat1,cat2,cat3,cat4,cat5,cat6,cat7,cat8,cat9
0,0,20073966,22589171,0,-1,-1,0,0,-1,-1,...,-1,5824233,9312274,3490278,29196072,11409686,1973606,25162884,29196072,29196072
1,2,24607497,884761,0,-1,-1,0,0,-1,-1,...,423858,30763035,9312274,14584482,29196072,11409686,1973606,22644417,9312274,21091111
2,2,28474333,18975823,0,-1,-1,0,0,-1,-1,...,8879,138937,9312274,10769841,29196072,5824237,138937,1795451,29196072,15351056
3,3,7306395,29427842,1,1449193,3063962,0,1,0,7,...,-1,28928366,26597095,12435261,23549932,5824237,1973606,9180723,29841067,29196072
4,3,25357769,13365547,0,-1,-1,0,0,-1,-1,...,-1,138937,26597094,31616034,29196072,11409684,26597096,4480345,29196072,29196072

Step 2: Data scale

In [3]:
df.shape

(1000000, 22)

Step 3: Data columns

In [4]:
df.columns.tolist()

['timestamp',
 'uid',
 'campaign',
 'conversion',
 'conversion_timestamp',
 'conversion_id',
 'attribution',
 'click',
 'click_pos',
 'click_nb',
 'cost',
 'cpo',
 'time_since_last_click',
 'cat1',
 'cat2',
 'cat3',
 'cat4',
 'cat5',
 'cat6',
 'cat7',
 'cat8',
 'cat9']

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 22 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   timestamp              1000000 non-null  int64
 1   uid                    1000000 non-null  int64
 2   campaign               1000000 non-null  int64
 3   conversion             1000000 non-null  int64
 4   conversion_timestamp   1000000 non-null  int64
 5   conversion_id          1000000 non-null  int64
 6   attribution            1000000 non-null  int64
 7   click                  1000000 non-null  int64
 8   click_pos              1000000 non-null  int64
 9   click_nb               1000000 non-null  int64
 10  cost                   1000000 non-null  float64
 11  cpo                    1000000 non-null  float64
 12  time_since_last_click  1000000 non-null  int64
 13  cat1                   1000000 non-null  int64
 14  cat2                   1000000 non-null  int64
 15  cat3                   1000000 non-null  int64
 16  cat4                   1000000 non-null  int64
 17  cat5                   1000000 non-null  int64
 18  cat6                   1000000 non-null  int64
 19  cat7                   1000000 non-null  int64
 20  cat8                   1000000 non-null  int64
 21  cat9                   1000000 non-null  int64
dtypes: float64(2), int64(20)
memory usage: 167.8 MB

Step 4. Missing values check

In [6]:
df.isnull().mean().sort_values(ascending=False)

timestamp                0.0
uid                      0.0
cat8                     0.0
cat7                     0.0
cat6                     0.0
cat5                     0.0
cat4                     0.0
cat3                     0.0
cat2                     0.0
cat1                     0.0
time_since_last_click    0.0
cpo                      0.0
cost                     0.0
click_nb                 0.0
click_pos                0.0
click                    0.0
attribution              0.0
conversion_id            0.0
conversion_timestamp     0.0
conversion               0.0
campaign                 0.0
cat9                     0.0
dtype: float64

Step 5. Key metrics

In [7]:
df[["click", "conversion", "attribution"]].mean()

click          0.344946
conversion     0.048557
attribution    0.026872
dtype: float64

Step 6: The number of campaigns

In [8]:
df["campaign"].nunique()

670

Step 7: Category feature cardinality

In [9]:
for c in [f"cat{i}" for i in range(1, 10)]:
    print(c, df[c].nunique())

cat1 9
cat2 65
cat3 1684
cat4 20
cat5 50
cat6 30
cat7 20789
cat8 11
cat9 30

In [10]:
df[["cost", "cpo", "time_since_last_click"]].describe()

                 cost             cpo  time_since_last_click
count  1000000.000000  1000000.000000           1.000000e+06
mean         0.000276        0.183385           2.792014e+05
std          0.000817        0.115319           5.248693e+05
min          0.000010        0.004000          -1.000000e+00
25%          0.000024        0.094231          -1.000000e+00
50%          0.000075        0.177205          -1.000000e+00
75%          0.000224        0.257981           2.934672e+05
max          0.054845        0.990308           2.565379e+06